version: "3"

services:

  phonebook:
    container_name: phonebook
    #image: denisnovac/scala-phonebook
    build: .
    networks:
      overlay:
        ipv4_address: 172.18.1.2
    ports:
      - "9000:9000"
    volumes:
      - "./application.conf:/opt/app/application.conf"

  db:
    container_name: db
    image: postgres:alpine
    networks:
      overlay:
        ipv4_address: 172.18.1.10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    #volumes:
    #  - "./db:/var/lib/postgresql/data"

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    depends_on:
      - phonebook
    networks:
      overlay:
        ipv4_address: 172.18.1.3
    ports:
      - "80:8080"
    environment:
      - URL=http://172.18.1.2:9000/api




networks:
  overlay:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
